version: "3.1"

services:
  django_server:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    command: python entrypoint.py 9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    networks:
      - backbone

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: utkarsh
  #     POSTGRES_DB: practice
  #   ports: 
  #     - "5432:5432"
  #   volumes: 
  #     - ./postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - backbone

networks:
  backbone:
    driver: bridge
