# Generated by Django 5.2 on 2025-04-26 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.IntegerField()),
                ('is_board', models.BooleanField()),
            ],
            options={
                'db_table': 'class_master',
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject_type', models.CharField(blank=True, choices=[('theory', 'Theory'), ('practical', 'Practical'), ('both', 'Both')], max_length=20, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject_master',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('admission_date', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.classes')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subjects')),
            ],
            options={
                'db_table': 'student_subject_mapping',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('teacher_email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('qualifications', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20)),
                ('role', models.CharField(choices=[('tgt', 'TGT'), ('pgt', 'PGT'), ('prt', 'PRT'), ('ntt', 'NTT'), ('other', 'Other')], max_length=20)),
                ('primary_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subjects')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentParentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian')], max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.parents')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.students')),
            ],
            options={
                'db_table': 'student_parent_mapping',
                'indexes': [models.Index(fields=['student_id'], name='student_par_student_0760ae_idx'), models.Index(fields=['parent_id'], name='student_par_parent__15ff09_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_id', 'parent_id'), name='unique_student_parent_mapping')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectClassMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.teachers')),
            ],
            options={
                'db_table': 'teacher_subject_class_mapping',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'classes'), name='unique_teacher_subject_class')],
            },
        ),
    ]
